import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ColorSettingsProvider } from '@/context/ColorSettingsContext';

export const metadata: Metadata = {
  title: "plshchkv",
  description: "Generated by create next app"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ColorSettingsProvider>
          {children}
        </ColorSettingsProvider>
      </body>
    </html>
  );
}
